### ISSUE TITLE
Progressive scan creates distorted image for widths 180 and 360

### ISSUE THREAD

**Issue by RobertLabonte** [vstroebel/jpeg-encoder#2]
This is a great library! I found an issue when providing images with a width of 360 or 180 when progressive_scan is set to true. Issue goes away when progressive_scan is set to false. 

Input is RGB and encoder quality is set to 85. 

Image from Big Buck Bunny showing the distortion.
![test](https://user-images.githubusercontent.com/836268/153739247-9f6659ab-4a27-4a62-9c05-67fffb18ed07.jpg)

**Comment by RobertLabonte** [comment]
It looks like Chrome doesn't display the image. Click on the invisible link to get the URL of the image.

**Comment by vstroebel** [comment]
This is most likely a problem with subsampling. I've created #3 this should fix this problems. 
Would be nice if you can test if this PR fixes the Problem for your test image, too.

**Comment by RobertLabonte** [comment]
It's fixed. Thank you!
![test](https://user-images.githubusercontent.com/836268/153766823-cfdae494-a0ff-4303-ab2f-6fe0c85358dd.jpg)
