### ISSUE TITLE
Invalid encoding

### ISSUE THREAD

**Issue by sug0** [vstroebel/jpeg-encoder#4]
Using `jpeg-encoder v0.5.0`, I get the following picture:

![green circle](https://gandas.us.to/ipfs/bafkreighfqydsrl4zmhwtxu2qwxsni2hlaplc4w2o3riozrexpa5vj6uha)

Which should have been a red circle. To reproduce this, I am using the following code:

https://git.sr.ht/~sugo/feim/tree/jpeg-bug/item/examples/encode.rs

In turn, this code is calling into your library to perform the actual encoding:

https://git.sr.ht/~sugo/feim/tree/jpeg-bug/item/src/image/jpeg/mod.rs#L167

Could this be some logic error in my code, or is there an issue with the encoding process in your end? If I switch the output format from jpeg to, for instance, farbfeld, this program works as expected.

**Comment by vstroebel** [comment]
This was a bug in the encoder. I've released 0.5.1 that should fix this.

**Comment by sug0** [comment]
Thank you! :)
